.PHONY: build run test clean fmt clippy

build:
	cargo build --release

run:
	cargo run

dev:
	cargo run

test:
	cargo test

clean:
	cargo clean
	rm -rf uploads clips

fmt:
	cargo fmt

clippy:
	cargo clippy -- -D warnings

check:
	cargo check

